name: upload file
run-name: ${{ github.actor }} : testing GitHub Actions for upload file
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: "37.152.177.133"
          username: "ubuntu"
          password: "HRlYPxCPkF!"
          port: "22"
          source: README.md
          target: "~"