jobs:
  upload_to_drive:
      runs-on: ubuntu-latest
      needs: build
      strategy:
        matrix:
          flavor: [tinext, postino, tinextPos]
      steps:
        - uses: actions/checkout@v2
        - name: Copy files via SSH
          uses: appleboy/scp-action@master
          with:
            host: "37.152.177.133"
            username: "ubuntu"
            password: "HRlYPxCPkF!"
            port: "22"
            source: README.md
            target: "~"